name: keep-service-alive

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-ping-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
        with:
          bash-version: 5.x
      - name: run bash script
        run: bash keep-service-alive.sh
